income_statement_metrics = ["Revenue", "Revenue Growth", "Cost of Revenue", "Gross Profit", "R&D Expenses",
                            "SG&A Expense", "Operating Expenses", "Operating Income", "Interest Expense",
                            "Earnings before Tax", "Income Tax Expense", "Net Income - Non-Controlling int",
                            "Net Income - Discontinued ops", "Net Income", "Preferred Dividends", "Net Income Com",
                            "EPS", "EPS Diluted", "Shares (basic)", "Shares (weighted)", "Shares (weighted, diluted)",
                            "Dividend per Share", "Gross Margin", "EBITDA Margin", "EBIT Margin", "Profit Margin",
                            "Free Cash Flow margin", "EBITDA", "EBIT", "Consolidated Income",
                            "Earnings Before Tax Margin", "Net Profit Margin"]
metrics_statement_metrics = ["Net Income per Share", "Operating Cash Flow per Share", "Free Cash Flow per Share",
                             "Cash per Share", "Book Value per Share", "Tangible Book Value per Share",
                             "Shareholders Equity per Share", "Interest Debt per Share", "Market Cap",
                             "Enterprise Value" "PE ratio", "PS ratio", "POCF ratio", "PFCF ratio", "PB ratio",
                             "PTB ratio", "EV to Sales", "EV to EBITDA", "EV to Operating cash flow",
                             "EV to Free cash flow", "Earnings Yield", "Free Cash Flow Yield", "Debt to Equity",
                             "Debt to Assets", "Net Debt to EBITDA", "Current ratio",
                             "Interest Coverage", "Income Quality", "Dividend Yield", "Payout Ratio",
                             "SG&A to Revenue", "R&D to Revenue", "Intangibles to Total Assets",
                             "Capex to Operating Cash Flow", "Capex to Revenue", "Capex to Depreciation",
                             "Stock-based compensation to Revenue", "Graham Number", "Graham Net-Net",
                             "Working Capital", "Tangible Asset Value", "Net Current Asset Value", "Invested Capital",
                             "Average Receivables", "Average Payables", "Average Inventory", "Capex per Share",
                             "Free Cash Flow per Share"]
balance_sheet_metrics = ["Cash and cash equivalents", "Short-term investments", "Cash and short - term investments",
                         "Receivables", "Inventories", "Total current assets", "Property, Plant & Equipment Net",
                         "Goodwill and Intangible Assets", "Long - term investments", "Tax assets",
                         "Total non - current",
                         "assets", "Total assets", "Payables", "Short - term debt", "Total current liabilities",
                         "Long - term debt", "Total debt", "Deferred revenue", "Tax Liabilities", "Deposit Liabilities",
                         "Total non - current liabilities", "Total liabilities", "Other comprehensive income",
                         "Retained earnings(deficit)", "Total shareholders equity", "Investments", "Net Debt",
                         "Other Assets Other Liabilities"]
cash_statement_metrics = ["Depreciation & Amortization", "Stock-based compensation", "Operating Cash Flow", "Capital",
                          "Expenditure", "Acquisitions and disposals", "Investment purchases and sales",
                          "Investing Cash flow", "Issuance (repayment) of debt", "Issuance (buybacks) of shares",
                          "Dividend payments", "Financing Cash Flow", "Effect of forex changes on cash",
                          "Net cash flow / Change in cash", "Free Cash Flow", "Net Cash/ Marketcap"]
